mode: "wgan-gp"
dataset: "gaussians25"
dim: 512
fix_generator: false
lambda1: 0.1
critic_iters: 5
batch_size: 256
iters: 100000
optimizer: "Adam"
lr: 0.0001
beta1: 0.5
beta2: 0.9
map_point_num: 128
map_point_range: 3
gpu: 0
log_dir: "./log/gaussians25"
